name: Build Python Package

on:  
  push:
  pull_request:
    branches:
      - master
      - develop

env:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Poetry
      uses: snok/install-poetry@v1
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install
        
    - name: Run code quality checks
      run: |
        poetry run python -m pylint jdataclass/
        poetry run python -m pyright jdataclass/
        poetry run python -m pytest
      